version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "python ./WoodWoorldStroy/manage.py makemigrations
      && python ./WoodWoorldStroy/manage.py migrate
      && exec python ./WoodWoorldStroy/manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=password

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: